language: go

# use containers which run faster and have cache
sudo: false

go:
  - 1.11.x

go_import_path: github.com/adamryman/counting

script:
  - go build ./...
  - go test ./...
  - go test -branch=.

notifications:
  email: false
